config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # get 'products/index'
  # get 'catagorys/index'
  # root "pages#home"
  root "catagorys#index"
  # get 'about' => 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :pages 
  resources :catagorys
  resources :products



  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_catagory
end

app/models/product_catagory.rb
class ProductCatagory < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catagorys_controller.rb
class CatagorysController < ApplicationController

  before_action :find_user, except: [:show, :index, :new, :create]

  def index
    @users = ProductCatagory.all
  end

  def show
    @user = ProductCatagory.find(params[:id])
    @shows = @user.products
  end

  def new
    @user = ProductCatagory.new
  end

  def edit
  end

  def create
    @user = ProductCatagory.new(params_pro)
    if @user.save
      flash[:success] = "Category successfully created"
      redirect_to @user
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def update
    if @user.update_attributes(params_pro)
      flash[:success] = "Category was successfully updated"
      redirect_to @user
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Category was successfully deleted"
      redirect_to @users_path
    else
      flash[:error] = "Something went wrong"
      redirect_to @users_path
    end
  end

  private
    def params_pro 
      params.require(:product_catagory).permit(:catagory_name)
    end

    def find_user
      @user = ProductCatagory.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_user, except: [:index, :new, :create]

  def index
    @users = Product.all
  end

  def show
  end

  def new
    @user = Product.new
  end

  def edit
  end

  def create
    @user = Product.new(params_product)
    if @user.save
      flash[:success] = "Product successfully created"
      redirect_to @user
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def update
    if @user.update_attributes(params_product)
      flash[:success] = "Product was successfully updated"
      redirect_to @user
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Product was successfully deleted"
      redirect_to @users_path
    else
      flash[:error] = "Something went wrong"
      redirect_to @users_path
    end
  end

  private
  def params_product 
    params.require(:product).permit(:product_name, :product_price, :product_catagory_id)
  end


    def find_user
      @user = Product.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagorys_helper.rb
module CatagorysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/catagorys/index.html.erb
<% @users.each do |a|%>
<a href="/catagorys/<%= a.id %>">
 <%= a.catagory_name %> <br>
<% end %>

<%= link_to "Createnew Product", new_product_path %>

app/views/catagorys/new.html.erb
<h1>New Article</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :catagory_name %><br>
    <%= form.text_field :catagory_name %>
    <% @user.errors.full_messages_for(:catagory_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/catagorys/show.html.erb
<% @shows.each do |s| %>
  <%= s.product_name  %>
  <%= s.product_price %><br>
<% end%>

app/views/layouts/_devise.html.erb
<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
  <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "navbar-link"  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
  <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
<% end %>
</p>

app/views/layouts/_stater.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopwib</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "layouts/stater" %>

  </head>
  <body> 
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       
    <%= render "layouts/devise" %>
  
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%=  link_to "catatory" , catagorys_path %>
<%= link_to "new", new_product_path %>

app/views/products/new.html.erb
<h1>New Article</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :product_name %><br>
    <%= form.text_field :product_name %>
    <% @user.errors.full_messages_for(:product_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :product_price %><br>
    <%= form.text_area :product_price %><br>
    <% @user.errors.full_messages_for(:product_price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
    <%= form.collection_select :product_catagory_id,  ProductCatagory.order(:catagory_name),:id,:catagory_name, include_blank: true %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/show.html.erb
<%= @user.product_name %>
<%=  @user.product_price %>